from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from dotenv import load_dotenv

from routes import router as api_router
from models import Base, engine

load_dotenv()

app = FastAPI(title="QueueBite API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router, prefix="/api/v1")


@app.on_event("startup")
def on_startup() -> None:
    Base.metadata.create_all(bind=engine)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/", response_class=HTMLResponse)
def landing():
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>QueueBite - AI Restaurant Queue Management</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0a0a0a;color:#e5e5e5;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:2rem}
.container{max-width:720px;width:100%}
.hero{text-align:center;margin-bottom:3rem}
.hero h1{font-size:2.8rem;font-weight:800;background:linear-gradient(135deg,#f97316,#ef4444);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:.5rem}
.hero .tagline{font-size:1.2rem;color:#a3a3a3;margin-bottom:1rem}
.badge{display:inline-block;padding:.3rem .8rem;border-radius:999px;font-size:.75rem;font-weight:600;margin:.2rem}
.badge-ai{background:#7c3aed22;color:#a78bfa;border:1px solid #7c3aed44}
.badge-do{background:#0080ff22;color:#60a5fa;border:1px solid #0080ff44}
.badge-live{background:#22c55e22;color:#4ade80;border:1px solid #22c55e44}
.card{background:#171717;border:1px solid #262626;border-radius:12px;padding:1.5rem;margin-bottom:1rem}
.card h2{font-size:1.1rem;font-weight:700;margin-bottom:1rem;color:#f5f5f5}
.endpoint{display:flex;align-items:center;gap:.75rem;padding:.6rem 0;border-bottom:1px solid #262626}
.endpoint:last-child{border-bottom:none}
.method{font-size:.7rem;font-weight:700;padding:.25rem .5rem;border-radius:4px;min-width:3.5rem;text-align:center}
.method-post{background:#3b82f622;color:#60a5fa}.method-get{background:#22c55e22;color:#4ade80}
.path{font-family:'SF Mono',Monaco,monospace;font-size:.85rem;color:#d4d4d4}
.desc{font-size:.78rem;color:#737373;margin-left:auto}
.links{display:flex;gap:.75rem;margin-top:1.5rem;justify-content:center;flex-wrap:wrap}
.links a{padding:.6rem 1.2rem;border-radius:8px;text-decoration:none;font-weight:600;font-size:.85rem;transition:all .15s}
.btn-primary{background:#f97316;color:#fff}.btn-primary:hover{background:#ea580c}
.btn-secondary{background:#262626;color:#d4d4d4;border:1px solid #404040}.btn-secondary:hover{background:#333}
.footer{text-align:center;margin-top:2rem;font-size:.75rem;color:#525252}
.footer a{color:#f97316;text-decoration:none}
</style>
</head>
<body>
<div class="container">
<div class="hero">
<h1>QueueBite</h1>
<p class="tagline">Scan, wait, dine &mdash; no more standing in line.</p>
<span class="badge badge-ai">AI-Powered</span>
<span class="badge badge-do">DigitalOcean</span>
<span class="badge badge-live">Live</span>
</div>
<div class="card">
<h2>API Endpoints</h2>
<div class="endpoint"><span class="method method-get">GET</span><span class="path">/health</span><span class="desc">Health check</span></div>
<div class="endpoint"><span class="method method-post">POST</span><span class="path">/api/v1/customers/join</span><span class="desc">Join restaurant queue</span></div>
<div class="endpoint"><span class="method method-get">GET</span><span class="path">/api/v1/customers/{queue_id}/status</span><span class="desc">Check queue position</span></div>
<div class="endpoint"><span class="method method-post">POST</span><span class="path">/api/v1/ai/predict-wait-time</span><span class="desc">AI wait time prediction</span></div>
<div class="endpoint"><span class="method method-post">POST</span><span class="path">/api/v1/ai/forecast-demand</span><span class="desc">AI demand forecasting</span></div>
</div>
<div class="card">
<h2>Tech Stack</h2>
<p style="color:#a3a3a3;font-size:.85rem;line-height:1.6">
FastAPI &bull; PostgreSQL &bull; SQLAlchemy &bull; DigitalOcean Serverless Inference (openai-gpt-oss-120b) &bull; Python 3.12
</p>
</div>
<div class="links">
<a href="/docs" class="btn-primary">Interactive API Docs</a>
<a href="/redoc" class="btn-secondary">ReDoc</a>
<a href="/openapi.json" class="btn-secondary">OpenAPI Spec</a>
</div>
</div>
<p class="footer">Generated by <a href="https://github.com/Two-Weeks-Team/vibeDeploy">vibeDeploy</a> &bull; Powered by <a href="https://www.digitalocean.com/products/gradient-ai">DigitalOcean Gradient AI</a></p>
</body>
</html>"""
